FROM python:3.10-alpine
WORKDIR /doodle/backend/test/

RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY tests/unit/test_schema.py .
COPY schema.py .

ENV REDIS_OM_URL=redis://dbase:6379

CMD ["python", "-m", "unittest", "-v", "test_schema.py"]