---
apiVersion: v1
kind: Service
metadata:
  name: dd-server
  namespace: doodle
  labels:
    app: server
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: server
    tier: backend
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dd-pv-claim
  namespace: doodle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-server
  namespace: doodle
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
      tier: backend
  template:
    metadata:
      labels:
        app: server
        tier: backend
    spec:
      containers:
      - image: zekissel/dd-server:main
        name: dd-server
        env:
        - name: REDIS_OM_URL
          value: redis://redis-service:6379
        ports:
        - containerPort: 8000
          name: server-port
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /var/www/html
          name: dd-pv-claim
      volumes:
      - name: dd-pv-claim
        persistentVolumeClaim:
          claimName: dd-pv-claim