name: Build Production Client

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout main
          uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '21.x'

        - name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
                ${{ runner.os }}-node-
    

        - name: Install dependencies and build dist
          working-directory: ./dd-client
          run: |
            npm ci
            npm run build

        - name: Upload distribution aritfacts
          uses: actions/upload-artifact@v2
          with:
            name: dist
            path: ./dd-client/dist

        - name: Checkout prod branch
          uses: actions/checkout@v2
          with:
            ref: prod

        - name: Download distribution directory
          uses: actions/download-artifact@v2
          with:
            name: dist
            path: ./dd-server

        - name: Commit build to production branch
          working-directory: ./
          env:
            GITHUB_TOKEN: ${{ github.token }}
          run: |
            mv ./dd-server/index.html ./dd-server/dist/
            mv ./dd-server/assets/* ./dd-server/dist/assets/
            git config --global user.email "github-actions"
            git config --global user.name "github-actions@github.com"
            git add ./dd-server/dist/*
            git commit -m "Auto build production client"
            git push
