name: Build Production Client

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout main
          uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '21.x'

        - name: Install dependencies
          working-directory: ./dd-client
          run: npm install

        - name: Build
          working-directory: ./dd-client
          run: npm run build

        - name: Checkout production
          run: |
            git fetch origin prod:prod
            git checkout prod

        - name: Copy files
          working-directory: ./dd-server
          run: |
            git add -f dist
            git commit -m "automatic compilation of client html/assets"