name: Build Production Client

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout main
          uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '21.x'

        - name: Install dependencies
          working-directory: ./dd-client
          run: npm install

        - name: Build and commit to production branch
          working-directory: ./dd-client
          run: |
            npm run build
            git config --global user.name 'GitHub Action'
            git config --global user.email 'action@github.com'
            git stash -u -- ./dist/
            cd ..
            git fetch origin prod:prod --force
            git checkout -f prod
            cd ./dd-server
            git stash pop
            git add ./dist/
            git diff-index --quiet HEAD ||  git commit -am "automatic client html/assets build"
            git push origin prod