name: Build Production Client

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout main
          uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '21.x'

        - name: Install dependencies
          working-directory: ./dd-client
          run: npm install

        - name: Build
          working-directory: ./dd-client
          run: npm run build

        - name: Checkout production
          run: |
            git checkout -f prod
            git checkout main -- dd-client/dist
            git add -A
            git diff-index --quiet HEAD ||  git commit -am "automatic client html/assets build"
            git push origin prod