name: Build Production Packages

on:
    push:
        paths-ignore:
            - '.github/**'
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout main
          uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '21.x'

        - name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
                ${{ runner.os }}-node-
    

        - name: Install dependencies and build dist
          working-directory: ./dd-client
          run: |
            npm ci
            npm run build

        - name: Upload distribution aritfacts
          uses: actions/upload-artifact@v2
          with:
            name: dist
            path: ./dd-client/dist

        - name: Checkout prod branch
          uses: actions/checkout@v2
          with:
            ref: prod

        - name: Download distribution artifacts
          uses: actions/download-artifact@v2
          with:
            name: dist
            path: ./dd-server

        - name: Commit client build to production branch
          working-directory: ./
          env:
            GITHUB_TOKEN: ${{ github.token }}
          run: |
            mv ./dd-server/index.html ./dd-server/dist/
            mv ./dd-server/assets/*.css ./dd-server/dist/assets/main.css
            mv ./dd-server/assets/*.js ./dd-server/dist/assets/main.js
            sed -i 's@"/assets/index.*css"@"/assets/main.css"@' ./dd-server/dist/index.html
            export INTEGRITY=$(cat ./dd-server/dist/assets/main.js | openssl dgst -sha384 -binary | openssl enc -base64 -A)
            sed -i "s@/assets/index.*js\"@/assets/main.js\" integrity=\"sha384-$INTEGRITY\"@" ./dd-server/dist/index.html

            git config --global user.email "dd-github-action"
            git config --global user.name "github-actions@github.com"
            git add ./dd-server/dist/*
            git diff-index --quiet HEAD || git commit -am "Auto compile production client"
            git push origin prod