name: Unit Test

on:
    push:
        branches:
            - main

jobs:
    unittest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10.13

            - name: Install dependencies
              working-directory: ./dd-server
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Launch services
              working-directory: .
              run: docker compose up -d

            - name: Run tests
              working-directory: ./dd-server/tests/unit
              run: |
                  python -m unittest -v test_schema.py